import type { PokemonType } from "./dex";

export const TYPE_TEXT_COLORS: Record<PokemonType, string> = {
  Normal:   "text-stone-400",
  Fire:     "text-orange-400",
  Water:    "text-blue-400",
  Electric: "text-yellow-300",
  Grass:    "text-green-400",
  Ice:      "text-cyan-300",
  Fighting: "text-red-500",
  Poison:   "text-purple-400",
  Ground:   "text-amber-500",
  Flying:   "text-indigo-400",
  Psychic:  "text-pink-400",
  Bug:      "text-lime-400",
  Rock:     "text-yellow-600",
  Ghost:    "text-purple-500",
  Dragon:   "text-blue-600",
  Dark:     "text-neutral-400",
  Steel:    "text-slate-400",
  Fairy:    "text-pink-300",
};

export const TYPE_COLORS: Record<PokemonType, string> = {
  Normal:   "bg-gradient-to-b from-stone-300 to-stone-500 text-white",
  Fire:     "bg-gradient-to-b from-orange-400 to-red-600 text-white",
  Water:    "bg-gradient-to-b from-blue-400 to-blue-600 text-white",
  Electric: "bg-gradient-to-b from-yellow-300 to-yellow-600 text-black",
  Grass:    "bg-gradient-to-b from-green-400 to-green-600 text-white",
  Ice:      "bg-gradient-to-b from-cyan-200 to-cyan-400 text-black",
  Fighting: "bg-gradient-to-b from-red-600 to-red-800 text-white",
  Poison:   "bg-gradient-to-b from-purple-400 to-purple-600 text-white",
  Ground:   "bg-gradient-to-b from-amber-500 to-amber-700 text-white",
  Flying:   "bg-gradient-to-b from-indigo-300 to-indigo-500 text-white",
  Psychic:  "bg-gradient-to-b from-pink-400 to-pink-600 text-white",
  Bug:      "bg-gradient-to-b from-lime-400 to-lime-600 text-white",
  Rock:     "bg-gradient-to-b from-yellow-700 to-yellow-900 text-white",
  Ghost:    "bg-gradient-to-b from-purple-700 to-purple-900 text-white",
  Dragon:   "bg-gradient-to-b from-[#1535A0] from-[35%] to-[#991b1b] text-white",
  Dark:     "bg-gradient-to-b from-neutral-600 to-neutral-800 text-white",
  Steel:    "bg-gradient-to-b from-slate-500 to-slate-600 text-white",
  Fairy:    "bg-gradient-to-b from-pink-200 to-pink-400 text-black",
};
